//! Channel implementations and orchestration for messaging platform integrations.

pub mod orchestrator;
pub mod util;

// Always-compiled utilities (no feature gate)
pub mod link_enricher;
pub mod transcription;
pub mod tts;

// Feature-gated channels
#[cfg(feature = "channel-bluesky")]
pub mod bluesky;
#[cfg(feature = "channel-clawdtalk")]
pub mod clawdtalk;
#[cfg(feature = "channel-dingtalk")]
pub mod dingtalk;
#[cfg(feature = "channel-discord")]
pub mod discord;
#[cfg(feature = "channel-discord")]
pub mod discord_history;
#[cfg(feature = "channel-email")]
pub mod email_channel;
#[cfg(feature = "channel-email")]
pub mod gmail_push;
#[cfg(feature = "channel-imessage")]
pub mod imessage;
#[cfg(feature = "channel-irc")]
pub mod irc;
#[cfg(feature = "channel-lark")]
pub mod lark;
#[cfg(feature = "channel-linq")]
pub mod linq;
#[cfg(feature = "channel-mattermost")]
pub mod mattermost;
#[cfg(feature = "channel-mochat")]
pub mod mochat;
#[cfg(feature = "channel-nextcloud")]
pub mod nextcloud_talk;
#[cfg(feature = "channel-nostr")]
pub mod nostr;
#[cfg(feature = "channel-notion")]
pub mod notion;
#[cfg(feature = "channel-qq")]
pub mod qq;
#[cfg(feature = "channel-reddit")]
pub mod reddit;
#[cfg(feature = "channel-signal")]
pub mod signal;
#[cfg(feature = "channel-slack")]
pub mod slack;
#[cfg(feature = "channel-twitter")]
pub mod twitter;
#[cfg(feature = "channel-voice-call")]
pub mod voice_call;
#[cfg(feature = "voice-wake")]
pub mod voice_wake;
#[cfg(feature = "channel-wati")]
pub mod wati;
#[cfg(feature = "channel-webhook")]
pub mod webhook;
#[cfg(feature = "channel-wecom")]
pub mod wecom;
#[cfg(feature = "channel-whatsapp-cloud")]
pub mod whatsapp;
#[cfg(feature = "whatsapp-web")]
pub mod whatsapp_storage;
#[cfg(feature = "whatsapp-web")]
pub mod whatsapp_web;
