//! Docker sandbox (container isolation)
//!
//! The sandbox wraps every tool invocation with a container launch. When a
//! `compose_path` is configured, a `docker-compose` file is generated next
//! to the workspace and commands run as `docker compose -f <path> run
//! --rm sandbox <cmd>`. Without a compose path (tests, bare-bones usage),
//! we fall back to the historical `docker run …` form so the sandbox still
//! works in environments without compose.

use crate::security::traits::Sandbox;
use std::path::{Path, PathBuf};
use std::process::Command;

/// A host→container mount attached to every sandbox invocation.
#[derive(Debug, Clone)]
pub struct DockerMount {
    pub host_path: PathBuf,
    pub container_path: PathBuf,
    pub writable: bool,
}

impl DockerMount {
    fn volume_arg(&self) -> String {
        let mode = if self.writable { "rw" } else { "ro" };
        format!(
            "{}:{}:{}",
            self.host_path.display(),
            self.container_path.display(),
            mode
        )
    }
}

/// Service name declared inside the generated compose file. Kept private
/// so callers don't depend on the literal string.
const COMPOSE_SERVICE: &str = "sandbox";
/// Project name passed as `-p` so repeated `docker compose run` calls
/// share a single logical project (and `--rm` cleans up predictably).
const COMPOSE_PROJECT: &str = "zeroclaw-sandbox";

/// Docker sandbox backend
#[derive(Debug, Clone)]
pub struct DockerSandbox {
    image: String,
    mounts: Vec<DockerMount>,
    compose_path: Option<PathBuf>,
}

impl Default for DockerSandbox {
    fn default() -> Self {
        Self {
            image: "alpine:latest".to_string(),
            mounts: Vec::new(),
            compose_path: None,
        }
    }
}

impl DockerSandbox {
    pub fn new() -> std::io::Result<Self> {
        if Self::is_installed() {
            Ok(Self::default())
        } else {
            Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Docker not found",
            ))
        }
    }

    pub fn with_image(image: String) -> std::io::Result<Self> {
        if Self::is_installed() {
            Ok(Self {
                image,
                mounts: Vec::new(),
                compose_path: None,
            })
        } else {
            Err(std::io::Error::new(
                std::io::ErrorKind::NotFound,
                "Docker not found",
            ))
        }
    }

    /// Attach a host-path mount that will be added to every container run.
    /// The caller is responsible for ensuring `host_path` exists; Docker
    /// will fail the run otherwise.
    pub fn with_mount(mut self, mount: DockerMount) -> Self {
        self.mounts.push(mount);
        self
    }

    /// Opt in to the compose-based launch path. The compose file is
    /// (re)generated at `path` on first use; callers should pick a stable
    /// location (e.g. `<workspace>/sandbox.compose.yml`) so users can
    /// inspect or diff it.
    pub fn with_compose_path(mut self, path: PathBuf) -> Self {
        self.compose_path = Some(path);
        self
    }

    pub fn probe() -> std::io::Result<Self> {
        Self::new()
    }

    fn is_installed() -> bool {
        Command::new("docker")
            .arg("--version")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }

    /// Render the compose YAML for this sandbox configuration. Kept as a
    /// pure function so tests can assert on the shape without touching
    /// the filesystem.
    pub(crate) fn render_compose_yaml(&self) -> String {
        let mut y = String::new();
        y.push_str(
            "# Auto-generated by ZeroClaw — shell sandbox container config.\n\
             # Regenerated each time the daemon starts; edits here are overwritten.\n",
        );
        y.push_str("services:\n");
        y.push_str(&format!("  {COMPOSE_SERVICE}:\n"));
        y.push_str(&format!("    image: {}\n", self.image));
        y.push_str("    network_mode: none\n");
        y.push_str("    mem_limit: 512m\n");
        y.push_str("    cpus: 1.0\n");
        if !self.mounts.is_empty() {
            y.push_str("    volumes:\n");
            for m in &self.mounts {
                y.push_str(&format!("      - \"{}\"\n", m.volume_arg()));
            }
        }
        y
    }

    fn ensure_compose_written(&self, path: &Path) -> std::io::Result<()> {
        let target = self.render_compose_yaml();
        if let Ok(existing) = std::fs::read_to_string(path) {
            if existing == target {
                return Ok(());
            }
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, target)
    }
}

impl Sandbox for DockerSandbox {
    fn wrap_command(&self, cmd: &mut Command) -> std::io::Result<()> {
        let program = cmd.get_program().to_string_lossy().to_string();
        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        let mut docker_cmd = Command::new("docker");

        match &self.compose_path {
            Some(path) => {
                self.ensure_compose_written(path)?;
                docker_cmd.args(["compose", "-p", COMPOSE_PROJECT, "-f"]);
                docker_cmd.arg(path);
                docker_cmd.args(["run", "--rm", "--no-deps", COMPOSE_SERVICE]);
                docker_cmd.arg(&program);
                docker_cmd.args(&args);
            }
            None => {
                docker_cmd.args([
                    "run",
                    "--rm",
                    "--memory",
                    "512m",
                    "--cpus",
                    "1.0",
                    "--network",
                    "none",
                ]);
                for mount in &self.mounts {
                    docker_cmd.arg("--volume").arg(mount.volume_arg());
                }
                docker_cmd.arg(&self.image);
                docker_cmd.arg(&program);
                docker_cmd.args(&args);
            }
        }

        *cmd = docker_cmd;
        Ok(())
    }

    fn is_available(&self) -> bool {
        Self::is_installed()
    }

    fn name(&self) -> &str {
        "docker"
    }

    fn description(&self) -> &str {
        "Docker container isolation (requires docker)"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn docker_sandbox_name() {
        let sandbox = DockerSandbox::default();
        assert_eq!(sandbox.name(), "docker");
    }

    #[test]
    fn docker_sandbox_default_image() {
        let sandbox = DockerSandbox::default();
        assert_eq!(sandbox.image, "alpine:latest");
    }

    #[test]
    fn docker_with_custom_image() {
        let result = DockerSandbox::with_image("ubuntu:latest".to_string());
        match result {
            Ok(sandbox) => assert_eq!(sandbox.image, "ubuntu:latest"),
            Err(_) => assert!(!DockerSandbox::is_installed()),
        }
    }

    // ── §1.1 Sandbox isolation flag tests ──────────────────────

    #[test]
    fn docker_wrap_command_includes_isolation_flags() {
        // Legacy docker-run path (no compose configured).
        let sandbox = DockerSandbox::default();
        let mut cmd = Command::new("echo");
        cmd.arg("hello");
        sandbox.wrap_command(&mut cmd).unwrap();

        assert_eq!(
            cmd.get_program().to_string_lossy(),
            "docker",
            "wrapped command should use docker as program"
        );

        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        assert!(
            args.contains(&"run".to_string()),
            "must include 'run' subcommand"
        );
        assert!(
            args.contains(&"--rm".to_string()),
            "must include --rm for auto-cleanup"
        );
        assert!(
            args.contains(&"--network".to_string()),
            "must include --network flag"
        );
        assert!(
            args.contains(&"none".to_string()),
            "network must be set to 'none' for isolation"
        );
        assert!(
            args.contains(&"--memory".to_string()),
            "must include --memory limit"
        );
        assert!(
            args.contains(&"512m".to_string()),
            "memory limit must be 512m"
        );
        assert!(
            args.contains(&"--cpus".to_string()),
            "must include --cpus limit"
        );
        assert!(args.contains(&"1.0".to_string()), "CPU limit must be 1.0");
    }

    #[test]
    fn docker_wrap_command_preserves_original_command() {
        let sandbox = DockerSandbox::default();
        let mut cmd = Command::new("ls");
        cmd.arg("-la");
        sandbox.wrap_command(&mut cmd).unwrap();

        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        assert!(
            args.contains(&"alpine:latest".to_string()),
            "must include the container image"
        );
        assert!(
            args.contains(&"ls".to_string()),
            "original program must be passed as argument"
        );
        assert!(
            args.contains(&"-la".to_string()),
            "original args must be preserved"
        );
    }

    #[test]
    fn docker_wrap_command_uses_custom_image() {
        let sandbox = DockerSandbox {
            image: "ubuntu:22.04".to_string(),
            mounts: Vec::new(),
            compose_path: None,
        };
        let mut cmd = Command::new("echo");
        sandbox.wrap_command(&mut cmd).unwrap();

        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        assert!(
            args.contains(&"ubuntu:22.04".to_string()),
            "must use the custom image"
        );
    }

    #[test]
    fn docker_wrap_command_emits_volume_flags_for_mounts() {
        let sandbox = DockerSandbox::default()
            .with_mount(DockerMount {
                host_path: PathBuf::from("/host/inbound"),
                container_path: PathBuf::from("/host/inbound"),
                writable: false,
            })
            .with_mount(DockerMount {
                host_path: PathBuf::from("/host/outbox"),
                container_path: PathBuf::from("/host/outbox"),
                writable: true,
            });

        let mut cmd = Command::new("ls");
        sandbox.wrap_command(&mut cmd).unwrap();

        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        assert!(
            args.iter().any(|a| a == "/host/inbound:/host/inbound:ro"),
            "read-only mount flag missing; got args: {args:?}"
        );
        assert!(
            args.iter().any(|a| a == "/host/outbox:/host/outbox:rw"),
            "read-write mount flag missing; got args: {args:?}"
        );
        let image_pos = args.iter().position(|a| a == "alpine:latest").unwrap();
        let last_volume_pos = args
            .iter()
            .enumerate()
            .rev()
            .find(|(_, a)| a.as_str() == "--volume")
            .map(|(i, _)| i)
            .unwrap();
        assert!(last_volume_pos < image_pos);
    }

    // ── Compose-backed launch path ─────────────────────────────

    #[test]
    fn compose_yaml_contains_service_image_and_mounts() {
        let sandbox = DockerSandbox::default()
            .with_mount(DockerMount {
                host_path: PathBuf::from("/data/inbound"),
                container_path: PathBuf::from("/data/inbound"),
                writable: false,
            })
            .with_mount(DockerMount {
                host_path: PathBuf::from("/data/outbox"),
                container_path: PathBuf::from("/data/outbox"),
                writable: true,
            });
        let yaml = sandbox.render_compose_yaml();
        assert!(yaml.contains("services:"));
        assert!(yaml.contains("sandbox:"));
        assert!(yaml.contains("image: alpine:latest"));
        assert!(yaml.contains("network_mode: none"));
        assert!(yaml.contains("mem_limit: 512m"));
        assert!(yaml.contains("cpus: 1.0"));
        assert!(yaml.contains("\"/data/inbound:/data/inbound:ro\""));
        assert!(yaml.contains("\"/data/outbox:/data/outbox:rw\""));
    }

    #[test]
    fn compose_yaml_omits_volumes_key_when_no_mounts() {
        let sandbox = DockerSandbox::default();
        let yaml = sandbox.render_compose_yaml();
        assert!(!yaml.contains("volumes:"));
    }

    #[test]
    fn wrap_command_uses_compose_when_path_configured() {
        let tmp = tempfile::tempdir().unwrap();
        let compose_path = tmp.path().join("sandbox.compose.yml");
        let sandbox = DockerSandbox::default()
            .with_mount(DockerMount {
                host_path: PathBuf::from("/data/inbound"),
                container_path: PathBuf::from("/data/inbound"),
                writable: false,
            })
            .with_compose_path(compose_path.clone());

        let mut cmd = Command::new("sh");
        cmd.arg("-c").arg("echo hello");
        sandbox.wrap_command(&mut cmd).unwrap();

        let args: Vec<String> = cmd
            .get_args()
            .map(|s| s.to_string_lossy().to_string())
            .collect();

        assert_eq!(args[0], "compose");
        assert!(args.iter().any(|a| a == "-p"));
        assert!(args.iter().any(|a| a == COMPOSE_PROJECT));
        assert!(args.iter().any(|a| a == "-f"));
        assert!(args.iter().any(|a| *a == compose_path.to_string_lossy()));
        assert!(args.iter().any(|a| a == "run"));
        assert!(args.iter().any(|a| a == "--rm"));
        assert!(args.iter().any(|a| a == COMPOSE_SERVICE));
        // Service name precedes the user command.
        let svc_pos = args.iter().position(|a| a == COMPOSE_SERVICE).unwrap();
        let prog_pos = args.iter().position(|a| a == "sh").unwrap();
        assert!(svc_pos < prog_pos);

        // Compose file must have been rendered to disk.
        let on_disk = std::fs::read_to_string(&compose_path).unwrap();
        assert!(on_disk.contains("image: alpine:latest"));
        assert!(on_disk.contains("/data/inbound:/data/inbound:ro"));
    }

    #[test]
    fn wrap_command_rewrites_compose_file_when_config_changes() {
        let tmp = tempfile::tempdir().unwrap();
        let compose_path = tmp.path().join("sandbox.compose.yml");

        let v1 = DockerSandbox::default().with_compose_path(compose_path.clone());
        let mut cmd = Command::new("ls");
        v1.wrap_command(&mut cmd).unwrap();
        let first = std::fs::read_to_string(&compose_path).unwrap();
        assert!(!first.contains("volumes:"));

        let v2 = DockerSandbox::default()
            .with_mount(DockerMount {
                host_path: PathBuf::from("/data/outbox"),
                container_path: PathBuf::from("/data/outbox"),
                writable: true,
            })
            .with_compose_path(compose_path.clone());
        let mut cmd = Command::new("ls");
        v2.wrap_command(&mut cmd).unwrap();
        let second = std::fs::read_to_string(&compose_path).unwrap();
        assert!(second.contains("/data/outbox:/data/outbox:rw"));
        assert_ne!(first, second);
    }
}
